name: Build Docs

on:
 push:
   branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: phpDocumentor
      run: |
        composer install
        composer bin phpdocumentor install
        composer run-script phpdoc
